baseurl = "http://jinlaixu.net/"
title = "Jinlai Xu's Homepage"
copyright = "&copy; 2017 Jinlai Xu"
theme = "academic"
enableEmoji = true
footnotereturnlinkcontents = "<sup>^</sup>"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true
paginate = 10

# Enable comments by entering your Disqus shortname
disqusShortname = "xujinlai"

# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics = "UA-46212341-5"

# Default language to use (if you setup multilingual support)
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[outputs]
  home = [ "HTML", "CSS" ]

[blackfriday]
  hrefTargetBlank = true

[params]
  # Color theme.
  #   Choose from `default`, `ocean`, `forest`, or `coffee`.
  color_theme = "default"
  
  # Font style.
  #   Choose from `default`, `classic`, or `playfair`.
  font = "default"
  
  # Your details.
  name = "Jinlai Xu (徐锦来)"
  role = "PhD Student"

  # Organizations/Affiliations.
  #   Separate multiple entries with a comma, using the form: `[ {name="Org1", url=""}, {name="Org2", url=""} ]`.
  organizations = [ { name = "University of Pittsburgh", url = "" } ]

  gravatar = false  # Get your avatar from Gravatar.com? (true/false)
  avatar = "avatar.jpg"  # Specify an avatar image (in `static/img/` folder) or delete value to disable avatar.
  email = "jinlai.xu@pitt.edu"
  address = "Information Sciences Bldg Room 410, 135 N Bellefield Ave, Pittsburgh, PA 15213, USA"
  office_hours = ""
  phone = ""
  skype = ""
  telegram = ""

  # Enable Keybase in Contact section by entering your keybase.io username.
  keybase = ""
  
  # Enable Google Maps by entering your API key, latitude, and longitude.
  #   Get your API key: https://developers.google.com/maps/documentation/javascript/get-api-key
  #   Get your coords: Right-click place on Google Maps. Select 'What's here?'. At the bottom is a card with the coords.
  #   Disable Google Maps by clearing all three options to "".
  google_maps_api_key = "AIzaSyCyUykjh2jO0V_zgje-GbdrjIahKHiCrqM"
  latitude = "40.447410"
  longitude = "-79.952636"

  # Date format (refer to Go's date format: http://flippinggodateformat.com )
  #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
  date_format = "Mon, Jan 2, 2006"
  
  # Show estimated reading time for posts?
  reading_time = true

  # Display comment count? Requires commenting to be enabled.
  comment_count = true
  
  # Display section pager for posts?
  section_pager = false

  # Enable global LaTeX math rendering?
  #   If false, you can enable it locally on a per page basis.
  math = false

  # Highlight.js options
  #   highlight
  #     Enable global source code highlighting?  If false, you can
  #     override it for a particular page in that page's preamble.
  #
  #     Example: highlight = true
  #
  #   highlight_languages
  #     Add support for highlighting additional languages. Support for
  #     languages mentioned here will be included in all pages. You
  #     can also set this variable for a particular page in that
  #     page's preamble.
  #
  #     Example: highlight_languages = ["go", "lisp", "ocaml"]
  #
  #   highlight_style
  #     Choose a different CSS style for highlighting source
  #     code. Setting this option in a page's preamble has no
  #     effect.
  #
  #     Example: highlight_style = "github-gist"
  #
  #   highlight_version
  #     Choose the version of highlight.js you want. Setting this
  #     option in a page's preamble has no effect.
  #
  #     Example: highlight_version = "9.9.0"
  #
  #   For the list of supported languages, styles, and versions, see:
  #   https://cdnjs.com/libraries/highlight.js/
  #
  #   For more info on the highlighting options, see:
  #   https://gcushen.github.io/hugo-academic-demo/post/writing-markdown-latex/#highlighting-options
  highlight = true
  highlight_languages = ["yaml"]
  highlight_style = "monokai-sublime"
  # highlight_version = "9.12.0"

  # Enable native social sharing buttons?
  sharing = true

  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  custom_css = ["custom.css"]
  custom_js  = []

  # Publication types.
  #   Used to categorize publications.
  #   The index of the publication type in the list is used as its unique numerical identifier.
  #   The numeric ID is used in a publication's frontmatter to categorize it.
  #   The language can be edited below.
  #   For multi-lingual sites, copy this block to each language section at the end of this file.
  publication_types = [
    'Uncategorized',  # 0
    'Conference proceedings',  # 1
    'Journal',  # 2
    'Work in progress',  # 3
    'Technical report',  # 4
    'Book',  # 5
    'Book chapter'  # 6
  ]

  # Social/Academic Networking
  #
  # Icon pack "fa" includes the following social network icons:
  #
  #   twitter, weibo, linkedin, github, facebook, pinterest, google-plus,
  #   youtube, instagram, soundcloud
  #
  #   For email icon, use "fa" icon pack, "envelope" icon, and
  #   "mailto:your@email.com" as the link.
  #
  #   Full list: https://fortawesome.github.io/Font-Awesome/icons/
  #
  # Icon pack "ai" includes the following academic network icons:
  #
  #   google-scholar, arxiv, orcid, researchgate, mendeley
  #
  #   Full list: https://jpswalsh.github.io/academicons/

  [[params.social]]
    icon = "envelope"
    icon_pack = "fa"
    link = "mailto:jinlai.xu@pitt.edu"

  [[params.social]]
    icon = "linkedin"
    icon_pack = "fa"
    link = "//www.linkedin.com/in/jinlaixu"

  [[params.social]]
    icon = "twitter"
    icon_pack = "fa"
    link = "//twitter.com/xujinlai"

  [[params.social]]
    icon = "google-scholar"
    icon_pack = "ai"
    link = "https://scholar.google.com/citations?user=OQjl2aIAAAAJ"

	[[params.social]]
    icon = "researchgate"
    icon_pack = "ai"
    link = "https://www.researchgate.net/profile/Jinlai_Xu"
	
	[[params.social]]
    icon = "orcid"
    icon_pack = "ai"
    link = "https://orcid.org/0000-0003-0032-5481"

  [[params.social]]
    icon = "github"
    icon_pack = "fa"
    link = "//github.com/xujinlai"


# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[menu.main]]
  name = "Home"
  url = "#about"
  weight = 1

[[menu.main]]
  name = "Publications"
  url = "#publications_selected"
  weight = 2

[[menu.main]]
  name = "Recent Posts"
  url = "#posts"
  weight = 3

[[menu.main]]
  name = "Projects"
  url = "#projects"
  weight = 4

[[menu.main]]
  name = "Teaching"
  url = "#teaching"
  weight = 5

[[menu.main]]
  name = "Services"
  url = "#professional_services"
  weight = 6
  

[[menu.main]]
  name = "Contact"
  url = "#contact"
  weight = 7
  
[[menu.main]]
  name = "Blog"
  url = "http://blog.jinlaixu.net"
  weight = 8

# Taxonomies.
[taxonomies]
  tag = "tags"
  category = "categories"
  publication_type = "publication_types"

# Languages
#   Create a [languages.X] block for each language you want, where X is the language ID.

# Configure the English version of the website.
[languages.en]
  languageCode = "en-us"
